// <auto-generated />
using System;
using GEE_Calculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GEE_Calculator.Migrations
{
    [DbContext(typeof(GeeCalculatorDbContext))]
    [Migration("20260511231402_AlignPostgresModelConstraints")]
    partial class AlignPostgresModelConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ActivityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_unit_id");

                    b.Property<decimal>("ActivityValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("activity_value");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("evidence_ref");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityUnitId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_activity_entries_category");

                    b.HasIndex("InventoryId");

                    b.HasIndex("MetadataJson")
                        .HasDatabaseName("ix_activity_entries_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadataJson"), "gin");

                    b.HasIndex("TenantId", "InventoryId")
                        .HasDatabaseName("ix_activity_entries_tenant_inventory");

                    b.ToTable("activity_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_entries_activity_value", "activity_value >= 0");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ActivityUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("dimension");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("activity_units", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("ActorExternalUserId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor_external_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.CalculationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_run_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GasId")
                        .HasColumnType("uuid")
                        .HasColumnName("gas_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalKgCo2e")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("total_kg_co2e");

                    b.HasKey("Id");

                    b.HasIndex("CalculationRunId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GasId");

                    b.HasIndex("Scope", "CategoryId")
                        .HasDatabaseName("ix_calculation_results_scope_category");

                    b.HasIndex("TenantId", "CalculationRunId")
                        .HasDatabaseName("ix_calculation_results_tenant_run");

                    b.ToTable("calculation_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_calculation_results_total_kg_co2e", "total_kg_co2e >= 0");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.CalculationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("calculation_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FactorSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_set_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("FactorSetId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("TenantId", "InventoryId")
                        .HasDatabaseName("ix_calculation_runs_tenant_inventory");

                    b.ToTable("calculation_runs", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalCompanyId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_company_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("trade_name");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ExternalCompanyId")
                        .IsUnique()
                        .HasFilter("external_company_id is not null");

                    b.HasIndex("TenantId", "TaxId")
                        .IsUnique()
                        .HasFilter("tax_id is not null");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Scope");

                    b.ToTable("emission_categories", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_unit_id");

                    b.Property<string>("CalculationNotes")
                        .HasColumnType("text")
                        .HasColumnName("calculation_notes");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FactorKgCo2ePerUnit")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("factor_kg_co2e_per_unit");

                    b.Property<decimal?>("FactorKgPerUnit")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("factor_kg_per_unit");

                    b.Property<Guid>("FactorSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_set_id");

                    b.Property<Guid?>("GasId")
                        .HasColumnType("uuid")
                        .HasColumnName("gas_id");

                    b.Property<decimal?>("Gwp")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("gwp");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityUnitId");

                    b.HasIndex("GasId");

                    b.HasIndex("CategoryId", "ActivityUnitId", "FactorSetId")
                        .HasDatabaseName("ix_emission_factors_lookup");

                    b.HasIndex("FactorSetId", "CategoryId", "ActivityUnitId", "GasId")
                        .IsUnique()
                        .HasDatabaseName("uq_emission_factors_global_lookup")
                        .HasFilter("tenant_id is null");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("FactorSetId", "CategoryId", "ActivityUnitId", "GasId"), false);

                    b.HasIndex("TenantId", "FactorSetId", "CategoryId", "ActivityUnitId", "GasId")
                        .IsUnique()
                        .HasDatabaseName("uq_emission_factors_tenant_lookup")
                        .HasFilter("tenant_id is not null");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "FactorSetId", "CategoryId", "ActivityUnitId", "GasId"), false);

                    b.ToTable("emission_factors", null, t =>
                        {
                            t.HasCheckConstraint("ck_emission_factors_factor_kg_co2e", "factor_kg_co2e_per_unit >= 0");

                            t.HasCheckConstraint("ck_emission_factors_factor_kg_per_unit", "factor_kg_per_unit is null or factor_kg_per_unit >= 0");

                            t.HasCheckConstraint("ck_emission_factors_gwp", "gwp is null or gwp > 0");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionFactorSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("version_label");

                    b.Property<int>("VersionYear")
                        .HasColumnType("integer")
                        .HasColumnName("version_year");

                    b.HasKey("Id");

                    b.HasIndex("Code", "VersionLabel")
                        .IsUnique();

                    b.HasIndex("SourceId", "VersionYear");

                    b.ToTable("emission_factor_sets", null, t =>
                        {
                            t.HasCheckConstraint("ck_emission_factor_sets_valid_range", "valid_to is null or valid_from is null or valid_to >= valid_from");

                            t.HasCheckConstraint("ck_emission_factor_sets_version_year", "version_year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionFactorSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("publisher");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("emission_factor_sources", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_emission_inventories_tenant_company");

                    b.HasIndex("TenantId", "CompanyId", "PeriodType", "Year")
                        .IsUnique()
                        .HasDatabaseName("uq_emission_inventories_period_annual")
                        .HasFilter("period_type = 'annual'");

                    b.HasIndex("TenantId", "CompanyId", "PeriodType", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_emission_inventories_period_monthly")
                        .HasFilter("period_type = 'monthly'");

                    b.ToTable("emission_inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_emission_inventories_month", "month is null or month between 1 and 12");

                            t.HasCheckConstraint("ck_emission_inventories_period_month", "(period_type = 'monthly' and month is not null) or (period_type = 'annual' and month is null)");

                            t.HasCheckConstraint("ck_emission_inventories_year", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ExternalUserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("external_user_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Provider", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("external_user_identities", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.GreenhouseGas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultGwp")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("default_gwp");

                    b.Property<string>("GwpSource")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("gwp_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("VersionYear")
                        .HasColumnType("integer")
                        .HasColumnName("version_year");

                    b.HasKey("Id");

                    b.HasIndex("Code", "VersionYear")
                        .IsUnique();

                    b.ToTable("greenhouse_gases", null, t =>
                        {
                            t.HasCheckConstraint("ck_greenhouse_gases_default_gwp", "default_gwp > 0");

                            t.HasCheckConstraint("ck_greenhouse_gases_version_year", "version_year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalTenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_tenant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTenantId")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ActivityEntry", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.ActivityUnit", null)
                        .WithMany()
                        .HasForeignKey("ActivityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionInventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ApiClient", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.CalculationResult", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.CalculationRun", null)
                        .WithMany()
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GEE_Calculator.Domain.Entities.GreenhouseGas", null)
                        .WithMany()
                        .HasForeignKey("GasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.CalculationRun", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionFactorSet", null)
                        .WithMany()
                        .HasForeignKey("FactorSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionInventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.Company", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionCategory", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionFactor", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.ActivityUnit", null)
                        .WithMany()
                        .HasForeignKey("ActivityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionFactorSet", null)
                        .WithMany()
                        .HasForeignKey("FactorSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.GreenhouseGas", null)
                        .WithMany()
                        .HasForeignKey("GasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionFactorSet", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.EmissionFactorSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.EmissionInventory", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GEE_Calculator.Domain.Entities.ExternalUserIdentity", b =>
                {
                    b.HasOne("GEE_Calculator.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
